services:
  mongo:
    image: mongo:7
    container_name: watchtower-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build: ./backend
    container_name: watchtower-backend
    ports:
      - '5001:5001'
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/watchtower
    depends_on:
      - mongo
    restart: always

  api-gateway:
    build: 
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    container_name: watchtower-gateway
    ports:
      - '4000:3000'
    environment:
      - DOCKER_ENV=true
    depends_on:
      - service-a
      - service-b
    restart: always

  service-a:
    build:
      context: ./backend/service-a
      dockerfile: Dockerfile
    container_name: watchtower-service-a
    ports:
      - '4001:3001'
    restart: always

  service-b:
    build:
      context: ./backend/service-b
      dockerfile: Dockerfile
    container_name: watchtower-service-b
    ports:
      - '4002:3002'
    restart: always

  frontend:
    build: ./frontend
    container_name: watchtower-frontend
    ports:
      - '8080:80'
    depends_on:
      - backend
      - api-gateway
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: watchtower-prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: watchtower-grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    container_name: watchtower-node-exporter
    ports:
      - '9100:9100'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)'
    restart: always

volumes:
  mongo_data:
  prometheus_data:
  grafana_data: